import './globals.scss';
import { Inter } from 'next/font/google';
import HeaderComponent from './HeaderComponent';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <HeaderComponent />
        <div className={inter.className}>{children}</div>
      </body>
    </html>
  );
}
